# Generated by Django 4.1.5 on 2023-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0002_alter_attendance_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.student'),
        ),
    ]
